> git push origin main:main
remote: error: Trace: 6551393fd0611e8dd7d9cb1a4902be7d3f66407cfb23a8d869936ac136b6de66        
remote: error: See https://gh.io/lfs for more information.        
remote: error: File analysis/インタラクティブ - TRVdata_fft_without_resampling.py.ipynb is 192.20 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
To https://github.com/ktr001/bache-thesis-python.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/ktr001/bache-thesis-python.git'
